# Generated by Django 3.1.9 on 2021-08-06 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.FileField(upload_to='problems/xmls/', verbose_name='input file')),
                ('zips', models.FileField(blank=True, upload_to='problems/zips/', verbose_name='zips')),
                ('txt', models.FileField(blank=True, upload_to='problems/txt/')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.FileField(upload_to='problems/xmls/', verbose_name='input file')),
                ('zips', models.FileField(blank=True, upload_to='problems/zips/', verbose_name='zips')),
                ('txt', models.FileField(blank=True, upload_to='problems/txt/')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_status', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProblemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.FileField(blank=True, upload_to='problems/parameters/weights/')),
                ('reference', models.FileField(blank=True, upload_to='problems/parameters/reference/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='molp_app.userproblem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProblemChebyshev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chebyshev', models.FileField(blank=True, upload_to='problems/chebyshev/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chebyshev', to='molp_app.userproblem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.FileField(blank=True, upload_to='problems/parameters/weights/')),
                ('reference', models.FileField(blank=True, upload_to='problems/parameters/reference/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='molp_app.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemChebyshev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chebyshev', models.FileField(blank=True, upload_to='problems/chebyshev/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chebyshev', to='molp_app.problem')),
            ],
        ),
    ]
