# Generated by Django 3.0.3 on 2020-04-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
