# Generated by Django 3.0.3 on 2020-07-23 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('molp_app', '0003_problem_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('xml', models.FileField(upload_to='problems/xmls/')),
                ('jobNumber', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.FileField(blank=True, upload_to='problems/solutions/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
