# Generated by Django 3.0.7 on 2020-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0004_userproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solver',
            field=models.CharField(choices=[('Gurobi', 'Gurobi'), ('NEOS', 'NEOS')], default='Gurobi', max_length=10),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='solver',
            field=models.CharField(choices=[('Gurobi', 'Gurobi'), ('NEOS', 'NEOS')], default='Gurobi', max_length=10),
        ),
    ]
