# Generated by Django 3.0.7 on 2020-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0006_auto_20200809_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='chebyshev',
            field=models.FileField(blank=True, upload_to='problems/chebeshev/'),
        ),
    ]
