# Generated by Django 3.0.7 on 2020-08-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0007_userproblem_chebyshev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblem',
            name='chebyshev',
            field=models.FileField(blank=True, upload_to='problems/chebyshev/'),
        ),
        migrations.CreateModel(
            name='UserProblemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfObjectives', models.IntegerField(blank=True, null=True)),
                ('weights', models.FileField(blank=True, upload_to='problems/parameters/')),
                ('reference', models.FileField(blank=True, upload_to='problems/parameters/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='molp_app.UserProblem')),
            ],
        ),
    ]
