# Generated by Django 3.1 on 2020-08-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0008_auto_20200817_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblemparameters',
            name='reference',
            field=models.FileField(blank=True, upload_to='problems/parameters/reference/'),
        ),
        migrations.AlterField(
            model_name='userproblemparameters',
            name='weights',
            field=models.FileField(blank=True, upload_to='problems/parameters/weights/'),
        ),
        migrations.CreateModel(
            name='ProblemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfObjectives', models.IntegerField(blank=True, null=True)),
                ('weights', models.FileField(blank=True, upload_to='problems/parameters/weights/')),
                ('reference', models.FileField(blank=True, upload_to='problems/parameters/reference/')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='molp_app.problem')),
            ],
        ),
    ]
