# Generated by Django 3.1 on 2020-08-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0011_singleobjectiveproblem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleObjectiveProblem',
        ),
    ]
