# Generated by Django 3.1 on 2021-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0012_delete_singleobjectiveproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='txt',
            field=models.FileField(blank=True, upload_to='problems/txt/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solver',
            field=models.CharField(choices=[('Gurobi', 'Gurobi'), ('NEOS', 'NEOS'), ('CBC', 'CBC')], default='Gurobi', max_length=10),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='solver',
            field=models.CharField(choices=[('Gurobi', 'Gurobi'), ('NEOS', 'NEOS'), ('CBC', 'CBC')], default='Gurobi', max_length=10),
        ),
    ]
