# Generated by Django 3.1 on 2021-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0014_auto_20210606_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solver',
            field=models.CharField(choices=[('NEOS', 'NEOS'), ('CBC', 'CBC')], default='CBC', max_length=10),
        ),
    ]
