# Generated by Django 3.1.9 on 2021-06-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0015_auto_20210606_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='txt',
            field=models.FileField(blank=True, upload_to='problems/txt/'),
        ),
    ]
