# Generated by Django 3.1.9 on 2021-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0018_problemchebyshev_chebyshev_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemchebyshev',
            name='chebyshev_zip',
        ),
        migrations.AddField(
            model_name='problem',
            name='chebyshev_zip',
            field=models.FileField(blank=True, upload_to='problems/zips/'),
        ),
    ]
