# Generated by Django 3.1.9 on 2021-07-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0022_auto_20210715_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemparameters',
            name='numberOfObjectives',
        ),
        migrations.RemoveField(
            model_name='userproblemparameters',
            name='numberOfObjectives',
        ),
    ]
