# Generated by Django 3.1.9 on 2021-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0023_auto_20210720_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='zips',
            field=models.FileField(blank=True, upload_to='problems/zips/', verbose_name='zips'),
        ),
    ]
