# Generated by Django 3.1.9 on 2021-07-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molp_app', '0025_auto_20210727_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='task_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
